Update new OVA related information
tidalmigrations/tidalmigrations.github.io pull request #182
Opened 2022-01-06 08:03 UTC by pranavmalaviya

A pass over the existing guides for Ubuntu 18.04 VM image since we have changed our approach from VMware as a builder to exporting OVA from the AWS EC2. This is also done to make the image available for public use.

2022-01-06 12:40 UTC, przmv commented on pages/user guides/tidal-vms.md
> +To help you get your Tidal Migrations discovery phase up and running, we've created a pre-configured virtual machines image. These VMs have the latest Tidal softwares and dependencies installed for y
“Software” is uncountable

2022-01-06 12:42 UTC, przmv requested changes
LGTM, just some minor fixes are required

2022-01-06 13:30 UTC, SamDesmondKing approved these changes
Looks good Pranav!

2022-01-06 13:30 UTC, SamDesmondKing commented on pages/user guides/tidal-vms.md
> +To help you get your Tidal Migrations discovery phase up and running, we've created a pre-configured virtual machine images. These VMs have the latest Tidal softwares and dependencies installed for y
Small grammar note, I think here you want `machine image` and `software` singular. Also `This VM has` etc if we're talking about a single one.

2022-01-06 13:31 UTC, SamDesmondKing commented on pages/user guides/tidal-vms.md
> +To help you get your Tidal Migrations discovery phase up and running, we've created a pre-configured virtual machine images. These VMs have the latest Tidal softwares and dependencies installed for y
Oh I just saw @przmv 's comment! Great minds think alike lol

2022-01-06 19:06 UTC, jmariomejiap approved these changes
Aside from Petr and Sam's comments, it looks good to go 🚀

2022-01-12 13:00 UTC, przmv commented on pages/user guides/tidal-vms.md
> +To help you get your Tidal Migrations discovery phase up and running, we've created a pre-configured virtual machine image. This VM has the latest Tidal software and dependencies installed for you, s
```suggestion
To help you get your Tidal Migrations discovery phase up and running, we've created a pre-configured virtual machine image. This VM has the latest Tidal Migrations software and dependencies installed for you, so you can focus on getting things done.
```

2022-01-12 13:01 UTC, przmv commented on pages/user guides/tidal-vms.md
>  summary: "Virtual machines pre-configured with Tidal software"
```suggestion
summary: "Virtual machines pre-configured with Tidal Migrations software"
```

2022-01-12 13:02 UTC, przmv requested changes
“Tidal softvare” vs “Tidal Migrations software”

2022-01-13 16:02 UTC, przmv approved these changes
LGTM

2022-01-13 16:13 UTC, merged